name: Kerberized Presto Integration Test

on:
  pull_request:
  push:
    branches:
      - master
      - 'release**'
      - 'feature**'
    tags:
      - '**'
    paths:
    - '**/presto_jdbc/**'
    - '**/presto_jdbc.clj'

jobs:
  run-presto-kerberos-test:
    # TODO: build some custom Docker image that pre-installs openjdk, babashka, docker-compose, etc.
    runs-on: ubuntu-20.04
    # container: metabase/presto-kerberos-mb-ci # your docker image
    timeout-minutes: 40
    steps:
      - name: Install babashka
        run: >
          mkdir -p /tmp/babashka-install \
            && cd /tmp/babashka-install \
            && curl -sLO https://raw.githubusercontent.com/babashka/babashka/master/install \
            && chmod +x install \
            && sudo ./install \
            && cd -
      - name: Install mba from zip file
        run: >
          curl https://www.dropbox.com/s/0gp6y860ldxatsq/mba-messing-with-volume-mounts.zip?dl=1 \
            -L --output /tmp/mba-src.zip
      - name: Unzip mba source
        run: unzip -d /tmp /tmp/mba-src.zip
      - name: Symlink mba
        run: sudo ln -s /tmp/mba-messing-with-volume-mounts/src/main.clj /usr/local/bin/mba
      - name: Ensure mba
        run: which mba
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Check out Presto Kerberos Docker Compose
        uses: actions/checkout@v2
        with:
          repository: metabase/presto-kerberos-docker
          ref: add-test_data-catalog
          token: ${{ secrets.GITHUB_TOKEN }}
          path: presto-kerberos-docker
      - name: Bring up Presto+Kerberos cluster
        run: cd presto-kerberos-docker && docker-compose up -d && cd ..
      - name: Run Presto test query from command line (sanity check)
        run: cd presto-kerberos-docker && ./test.sh && cd ..
      # Since we are managing the Docker containers from the GitHub action container, we need to copy all the
      # relevant resources now, into the resources dir for later consumption by the app
      - name: Copy Presto SSL keystore to resources
        run: docker cp presto-kerberos:/tmp/ssl_keystore.jks resources
      - name: Copy krb5.conf file to resources
        run: docker cp presto-kerberos:/etc/krb5.conf resources
      - name: Copy client.keytab file to resources
        run: docker cp presto-kerberos:/home/presto/client.keytab resources
      # TODO: figure out how to not need to do this
#      - name: Add .bashrc file (needed by mba for some reason)
#        run: >
#          mkdir -p /resources/home/ && touch /resources/home/.bashrc && touch /resources/home/.bash_profile
      - name: List files on host machine
        run: pwd && ls -latr
      - name: mba compose config
        run: mba --mb . --data-db postgres-data -n example.com compose config
      - name: Run Metabase via MBA
        run: set -x && mba --mb . --data-db postgres-data -n example.com up
      - name: mba run pwd
        run: mba --mb . --data-db postgres-data -n example.com run "pwd && ls -latr"
#      - name: mba logs
#        run: mba --mb . --data-db postgres-data -n example.com logs
#      - name: mba logs metabase
#        run: mba --mb . --data-db postgres-data -n example.com logs metabase
#      - name: mba run ls
#        run: mba --mb . --data-db postgres-data -n example.com run 'ls -latr'
#      - name: mba run ls test-scripts
#        run: mba --mb . --data-db postgres-data -n example.com run 'ls -latr test-scripts'
      - name: Run test script in MBA instance
        run: >
          mba --mb . --data-db postgres-data -n example.com \
           run test-scripts/run-presto-kerberos-integration-test.sh

